# Generated by Django 4.2.1 on 2023-05-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('pno', models.CharField(max_length=50, verbose_name='pno')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('dob', models.CharField(max_length=50, verbose_name='dob')),
                ('bg', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
